<!DOCTYPE HTML">
<html>
<head>
<link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>
<div style="position:absolute;top:0.65in;left:3.65in;width:1.78in;line-height:0.17in;">
    <span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Arial-BoldMT;color:#000000">RUKUN TETANGGA</span>
    <span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN>
</div>
<div style="position:absolute;top:0.96in;left:2.53in;width:4.00in;line-height:0.17in;">
    <span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Arial-BoldMT;color:#000000">KELURAHAN KIBING KECAMATAN BATU AJI</span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.28in;left:3.90in;width:1.27in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Arial-BoldMT;color:#000000">KOTA BATAM</span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.59in;left:1.56in;width:5.95in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:ArialMT;color:#000000">Ruko Bumi Agung Permai Blok B No. </span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:ArialMT;color:#000000">3A</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:ArialMT;color:#000000">, Nomor HP : +62813 7264 4481</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.80in;left:1.66in;width:5.75in;line-height:0.17in;"><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:ArialMT;color:#000000">Email Address : rt001rw021rukobap@gmail.com       Kode Pos : 29422</span><span style="font-style:normal;font-weight:normal;font-size:12pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<a href="mailto:rt001rw021rukobap@gmail.com">
</a><div style="position:absolute;top:2.43in;left:3.60in;width:1.88in;line-height:0.17in;"><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Arial-BoldMT;color:#000000">SURAT PENGANTAR</span><span style="font-style:normal;font-weight:bold;font-size:12pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.74in;left:4.36in;width:0.35in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">No :</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.24in;left:0.86in;width:7.35in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Ketua RT-</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">001</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> / RW-XXI Perumahan Bumi Agung Permai Kelurahan Kibing Kecamatan Batu Aji</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.53in;left:0.86in;width:2.66in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Kota Batam, menerangkan bahwa ;</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.10in;left:0.86in;width:1.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Nama Lengkap</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.10in;left:3.45in;width:0.09in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">:</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.39in;left:0.86in;width:1.08in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Jenis Kelamin</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.39in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">: </span></SPAN><br/></div>
<div style="position:absolute;top:4.39in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.67in;left:0.86in;width:1.77in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Tempat / Tanggal Lahir</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.67in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">: </span></SPAN><br/></div>
<div style="position:absolute;top:4.67in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.96in;left:0.86in;width:1.41in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Kewarganegaraan</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.96in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">: </span></SPAN><br/></div>
<div style="position:absolute;top:4.96in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.25in;left:0.86in;width:0.57in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Agama</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.25in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">: </span></SPAN><br/></div>
<div style="position:absolute;top:5.25in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.54in;left:0.86in;width:0.80in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Pekerjaan</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.54in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">: </span></SPAN><br/></div>
<div style="position:absolute;top:5.54in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.83in;left:0.86in;width:1.04in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">No. KTP / KK</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.83in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">: </span></SPAN><br/></div>
<div style="position:absolute;top:5.83in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.11in;left:0.86in;width:0.57in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Alamat</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.11in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">: </span></SPAN><br/></div>
<div style="position:absolute;top:6.11in;left:3.45in;width:0.18in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.69in;left:0.86in;width:7.35in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Bahwa benar nama tersebut diatas adalah penduduk / warga yang berdomisili diwilayah RT-</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">00</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">1 </span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">/</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.98in;left:0.86in;width:7.35in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">RW</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">-XXI Perumahan Bumi Agung Permai Kelurahan Kibing Kecamatan Batu Aji Kota Batam, Surat</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.26in;left:0.86in;width:3.06in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">pengantar ini diberikan untuk keperluan :</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.55in;left:0.86in;width:0.75in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Halo halo</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.03in;left:0.86in;width:0.74in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Demikian</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.03in;left:1.71in;width:0.45in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Surat</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.03in;left:2.27in;width:0.91in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Keterangan</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.03in;left:3.29in;width:0.21in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">ini</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.03in;left:3.61in;width:0.40in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">kami</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.03in;left:4.12in;width:0.37in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">buat</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.03in;left:4.60in;width:2.68in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">dengan </span></SPAN><br/></div>
<div style="position:absolute;top:8.03in;left:4.60in;width:2.68in;line-height:0.16in;"><DIV style="position:relative; left:0.71in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">sebenar-benarnya </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:8.03in;left:4.60in;width:2.68in;line-height:0.16in;"><DIV style="position:relative; left:2.23in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">untuk</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:8.03in;left:7.40in;width:0.81in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">digunakan</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.32in;left:0.86in;width:1.81in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">sebagaimana mestiny</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">a.</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.60in;left:5.77in;width:0.62in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Batam, </span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.89in;left:0.86in;width:0.96in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Mengetahui,</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.75in;left:0.86in;width:0.59in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Jabhari</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.75in;left:5.77in;width:1.58in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">            Zainul Efendi</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>

<div style="position:absolute;top:9.95in;left:0.86in;width:1.13in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">Ketua </span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">RW</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">-</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">XXI</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.95in;left:5.77in;width:1.59in;line-height:0.16in;"><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">           Ketua RT-</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000">001</span><span style="font-style:normal;font-weight:normal;font-size:11pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.28in;left:0.86in;width:0.69in;line-height:0.14in;"><span style="font-style:italic;font-weight:bold;font-size:10pt;font-family:Arial-BoldItalicMT;color:#000000">Catatan :</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.54in;left:1.54in;width:6.66in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:ArialMT;color:#000000">Surat Keterangan ini untuk 1 (satu) kali pengurusan </span></SPAN><br/></div>
<div style="position:absolute;top:10.54in;left:1.54in;width:6.66in;line-height:0.14in;"><DIV style="position:relative; left:3.67in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:ArialMT;color:#000000">dan </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.54in;left:1.54in;width:6.66in;line-height:0.14in;"><DIV style="position:relative; left:3.98in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:ArialMT;color:#000000">berlaku 1 (satu) </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.54in;left:1.54in;width:6.66in;line-height:0.14in;"><DIV style="position:relative; left:5.13in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:ArialMT;color:#000000">bulan setelah </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:10.54in;left:1.54in;width:6.66in;line-height:0.14in;"><DIV style="position:relative; left:6.12in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:ArialMT;color:#000000">tanggal</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.80in;left:1.54in;width:1.68in;line-height:0.14in;"><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:ArialMT;color:#000000">dikeluarkannya surat ini.</span><span style="font-style:normal;font-weight:normal;font-size:10pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
</body>
</html>
